// Generated by Axe Handle Test
const schema = {
  version: "DRAFT-2025-v1",
  interfaces: 67,
  types: 13,
  constants: 7
};


// Has initialize request



// Interface: Request

// Interface: Notification

// Interface: Result

